# Generated by Django 5.0.7 on 2024-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
