# Generated by Django 5.0.7 on 2024-08-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='hash',
        ),
        migrations.AddField(
            model_name='business',
            name='url_identifier',
            field=models.CharField(blank=True, editable=False, max_length=36, unique=True),
        ),
    ]
