# Generated by Django 5.0.7 on 2024-08-22 22:19

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_business_hash_business_url_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.banner_upload_path),
        ),
        migrations.AddField(
            model_name='business',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.icon_upload_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='src/static/images/default/image.png', upload_to=main.models.category_image_upload_path),
        ),
    ]
